/*
 * VisionConfig.h
 *
 *  Created on: Feb 27, 2014
 *      Author: nowireless
 */

#ifndef VISION_CONFIG_H_
#define VISION_CONFIG_H_


#define DEBUG_WRITE_IMAGE true

#define AREA_MINIMUM 150

#define SCORE_MAXPARTICLES 8

#define TARGET_VERTICAL_WIDTH (4.0)
#define TARGET_VERTICAL_HEIGHT (32.0)
#define TARGET_HORIZONTAL_WIDTH (23.5)
#define TARGET_HORIZONTAL_HEIGHT (4.0)

#define SCORING_RECTANGULARITY_LIMIT 40
#define SCORING_ASPECT_RATIO_LIMIT 30

#define ANALYSIS_TAPE_WIDTH_LIMIT		(40)
#define ANALYSIS_VERTICAL_SCORE_LIMIT	(40)
#define ANALYSIS_LR_SCORE_LIMIT			(40)

#endif /* VISION_H_ */
